export const errorTypes = {
  400: 'badRequest',
  401: 'unauthorized',
  402: 'paymentRequired',
  403: 'forbidden',
  404: 'notFound',
  405: 'methodNotAllowed',
  406: 'notAcceptable',
  407: 'proxyAuthenticationRequired',
  408: 'requestTimeout',
  409: 'conflict',
  410: 'gone',
  411: 'lengthRequired',
  412: 'preconditionFailed',
  413: 'payloadTooLarge',
  414: 'uriTooLong',
  415: 'unsupportedMediaType',
  416: 'rangeNotSatisfiable',
  417: 'expectationFailed',
  418: 'imATeapot', // April Fools' joke (RFC 2324)
  421: 'misdirectedRequest',
  422: 'unprocessableEntity',
  423: 'locked',
  424: 'failedDependency',
  426: 'upgradeRequired',
  428: 'preconditionRequired',
  429: 'tooManyRequests',
  431: 'requestHeaderFieldsTooLarge',
  451: 'unavailableForLegalReasons',
} as const;

export enum ErrorType {
  NOT_ACCESS_SESSION = 'noAccessSession',
  NOT_REFRESH_SESSION = 'noRefreshSession',
  INVALID_SESSION = 'invalidSession',
  EXPIRED_SESSION = 'expiredSession',
  EMAIL_NOT_VERIFIED = 'emailNotVerified',
  PERMISSION_DENIED = 'permissionDenied',
  USER_DISABLED = 'userDisabled',
}
